export interface Book {
  id: string;
  name: string;
  testament: 'old' | 'new';
  chapters: number;
}

export const bibleBooks: Book[] = [
  // Old Testament
  { id: 'genesis', name: 'Gênesis', testament: 'old', chapters: 50 },
  { id: 'exodus', name: 'Êxodo', testament: 'old', chapters: 40 },
  { id: 'leviticus', name: 'Levítico', testament: 'old', chapters: 27 },
  { id: 'numbers', name: 'Números', testament: 'old', chapters: 36 },
  { id: 'deuteronomy', name: 'Deuteronômio', testament: 'old', chapters: 34 },
  { id: 'joshua', name: 'Josué', testament: 'old', chapters: 24 },
  { id: 'judges', name: 'Juízes', testament: 'old', chapters: 21 },
  { id: 'ruth', name: 'Rute', testament: 'old', chapters: 4 },
  { id: '1samuel', name: '1 Samuel', testament: 'old', chapters: 31 },
  { id: '2samuel', name: '2 Samuel', testament: 'old', chapters: 24 },
  { id: '1kings', name: '1 Reis', testament: 'old', chapters: 22 },
  { id: '2kings', name: '2 Reis', testament: 'old', chapters: 25 },
  { id: '1chronicles', name: '1 Crônicas', testament: 'old', chapters: 29 },
  { id: '2chronicles', name: '2 Crônicas', testament: 'old', chapters: 36 },
  { id: 'ezra', name: 'Esdras', testament: 'old', chapters: 10 },
  { id: 'nehemiah', name: 'Neemias', testament: 'old', chapters: 13 },
  { id: 'esther', name: 'Ester', testament: 'old', chapters: 10 },
  { id: 'job', name: 'Jó', testament: 'old', chapters: 42 },
  { id: 'psalms', name: 'Salmos', testament: 'old', chapters: 150 },
  { id: 'proverbs', name: 'Provérbios', testament: 'old', chapters: 31 },
  { id: 'ecclesiastes', name: 'Eclesiastes', testament: 'old', chapters: 12 },
  { id: 'songofsolomon', name: 'Cânticos', testament: 'old', chapters: 8 },
  { id: 'isaiah', name: 'Isaías', testament: 'old', chapters: 66 },
  { id: 'jeremiah', name: 'Jeremias', testament: 'old', chapters: 52 },
  { id: 'lamentations', name: 'Lamentações', testament: 'old', chapters: 5 },
  { id: 'ezekiel', name: 'Ezequiel', testament: 'old', chapters: 48 },
  { id: 'daniel', name: 'Daniel', testament: 'old', chapters: 12 },
  { id: 'hosea', name: 'Oséias', testament: 'old', chapters: 14 },
  { id: 'joel', name: 'Joel', testament: 'old', chapters: 3 },
  { id: 'amos', name: 'Amós', testament: 'old', chapters: 9 },
  { id: 'obadiah', name: 'Obadias', testament: 'old', chapters: 1 },
  { id: 'jonah', name: 'Jonas', testament: 'old', chapters: 4 },
  { id: 'micah', name: 'Miquéias', testament: 'old', chapters: 7 },
  { id: 'nahum', name: 'Naum', testament: 'old', chapters: 3 },
  { id: 'habakkuk', name: 'Habacuque', testament: 'old', chapters: 3 },
  { id: 'zephaniah', name: 'Sofonias', testament: 'old', chapters: 3 },
  { id: 'haggai', name: 'Ageu', testament: 'old', chapters: 2 },
  { id: 'zechariah', name: 'Zacarias', testament: 'old', chapters: 14 },
  { id: 'malachi', name: 'Malaquias', testament: 'old', chapters: 4 },
  // New Testament
  { id: 'matthew', name: 'Mateus', testament: 'new', chapters: 28 },
  { id: 'mark', name: 'Marcos', testament: 'new', chapters: 16 },
  { id: 'luke', name: 'Lucas', testament: 'new', chapters: 24 },
  { id: 'john', name: 'João', testament: 'new', chapters: 21 },
  { id: 'acts', name: 'Atos', testament: 'new', chapters: 28 },
  { id: 'romans', name: 'Romanos', testament: 'new', chapters: 16 },
  { id: '1corinthians', name: '1 Coríntios', testament: 'new', chapters: 16 },
  { id: '2corinthians', name: '2 Coríntios', testament: 'new', chapters: 13 },
  { id: 'galatians', name: 'Gálatas', testament: 'new', chapters: 6 },
  { id: 'ephesians', name: 'Efésios', testament: 'new', chapters: 6 },
  { id: 'philippians', name: 'Filipenses', testament: 'new', chapters: 4 },
  { id: 'colossians', name: 'Colossenses', testament: 'new', chapters: 4 },
  { id: '1thessalonians', name: '1 Tessalonicenses', testament: 'new', chapters: 5 },
  { id: '2thessalonians', name: '2 Tessalonicenses', testament: 'new', chapters: 3 },
  { id: '1timothy', name: '1 Timóteo', testament: 'new', chapters: 6 },
  { id: '2timothy', name: '2 Timóteo', testament: 'new', chapters: 4 },
  { id: 'titus', name: 'Tito', testament: 'new', chapters: 3 },
  { id: 'philemon', name: 'Filemom', testament: 'new', chapters: 1 },
  { id: 'hebrews', name: 'Hebreus', testament: 'new', chapters: 13 },
  { id: 'james', name: 'Tiago', testament: 'new', chapters: 5 },
  { id: '1peter', name: '1 Pedro', testament: 'new', chapters: 5 },
  { id: '2peter', name: '2 Pedro', testament: 'new', chapters: 3 },
  { id: '1john', name: '1 João', testament: 'new', chapters: 5 },
  { id: '2john', name: '2 João', testament: 'new', chapters: 1 },
  { id: '3john', name: '3 João', testament: 'new', chapters: 1 },
  { id: 'jude', name: 'Judas', testament: 'new', chapters: 1 },
  { id: 'revelation', name: 'Apocalipse', testament: 'new', chapters: 22 },
];